# Server Port
server.port=8080
spring.application.name=PortfolioBackend

spring.config.import=optional:classpath:env.properties

# Static Resources (Keep this so Spring Boot can serve your HTML/CSS/JS)
spring.web.resources.static-locations=classpath:/static/

# Mail Configuration (Required for sending notifications)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Custom property to tell your Java code where to send the email
portfolio.contact.recipient=sourabhawate7474@gmail.com

#Handlinmg timeouts
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# CORS security (Required if you are testing from a different port, e.g., Live Server)
portfolio.cors.allowed-origins=http://localhost:63342,http://127.0.0.1:63342